export const BALANCE_SHEET_FETCH_SUCCESS = "BALANCE_SHEET_FETCH_SUCCESS";
export const BALANCE_SHEET_FETCH_FAILURE = "BALANCE_SHEET_FETCH_FAILURE";
export const DECISION_FETCH_SUCCESS = "DECISION_FETCH_SUCCESS";
export const DECISION_FETCH_ERROR = "DECISION_FETCH_ERROR";
